"""
    This file is to define common exception occurs during CRUD Operation.
"""

class UserNotFoundError(Exception): ...
class EmailAlreadyExist(Exception): ...
class PasswordMismatchError(Exception): ...

class CourseNotFoundError(Exception): ...
class CourseModuleNotFoundError(Exception): ...
class ResourceNotFoundError(Exception): ...

class UserAlreadyEnrolledError(Exception): ...
class EnrollmentNotFoundError(Exception): ...
class AdminEnrollmentNotAllowdedError(Exception): ...
class UserNotEnrolledError(Exception): ...

class TokenInvalidOrExpiredError(Exception): ...
class CourseNameAlreadyFoundError(Exception): ...
class ModuleNameAlreadyFoundError(Exception): ...
class ResourceNameAlreadyFoundError(Exception): ...

class CourseHasModulesError(Exception): ...
class ModuleHasResourcesError(Exception): ...
class UserHasDataError(Exception): ...