"""
    This file is to define common exception occurs during CRUD Operation.
"""

class UserNotFoundError(Exception): ...
class EmailAlreadyExist(Exception): ...
class PasswordMismatchError(Exception): ...

class CourseNotFoundError(Exception): ...
class CourseModuleNotFoundError(Exception): ...
class ResourceNotFoundError(Exception): ...

class UserAlreadyEnrolledError(Exception): ...
class EnrollmentNotFoundError(Exception): ...

class TokenInvalidOrExpiredError(Exception): ...